// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLIFpRidZIEN83TBWmCauGhq8UnBydGhc',
    appId: '1:313007119663:web:c78eab0ce6746f17e095da',
    messagingSenderId: '313007119663',
    projectId: 'firstbackend-application',
    authDomain: 'firstbackend-application.firebaseapp.com',
    storageBucket: 'firstbackend-application.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA75x40jq5lXFpV_H1AHlg5ygNnqwo19ls',
    appId: '1:313007119663:android:e928a325571e5364e095da',
    messagingSenderId: '313007119663',
    projectId: 'firstbackend-application',
    storageBucket: 'firstbackend-application.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMw-FPBSsCUC_rvw_7cYSp1IPNDCPQDMo',
    appId: '1:313007119663:ios:fbaa99ea23fdca93e095da',
    messagingSenderId: '313007119663',
    projectId: 'firstbackend-application',
    storageBucket: 'firstbackend-application.appspot.com',
    iosClientId: '313007119663-ubns9efmhu0ncrakkdsu25m8uvs2r421.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationBrewCrew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMw-FPBSsCUC_rvw_7cYSp1IPNDCPQDMo',
    appId: '1:313007119663:ios:14a997c292920d27e095da',
    messagingSenderId: '313007119663',
    projectId: 'firstbackend-application',
    storageBucket: 'firstbackend-application.appspot.com',
    iosClientId: '313007119663-1na4dbse7ab5o2buqov3l49gtvme0a4o.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationBrewCrew.RunnerTests',
  );
}
